language: elixir
elixir:
  - 1.8.2
sudo: false # to use faster container based build environment
notifications:
  recipients:
    - jose.valim@dashbit.co
otp_release:
  - 22.0
script:
  - if [[ $(elixir --version) = *"1.6"* ]]; then mix format --check-formatted; fi
  - mix test
matrix:
  include:
    - elixir: 1.5.1
      otp_release: 19.3
